repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
    -   id: double-quote-string-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.600
    hooks:
    -   id: mypy
